.PHONY: all gen-prime-baskets clean

# Python interpreter
PYTHON := python3

# Defalt target: Run the main proof
all: gen-prime-baskets

# Generate prime baskets
gen-prime-baskets:
	python3 all_prime_baskets.py

# Clean up pycache
clean:
	rm -rf __pycache__
